services:
  db:
    image: mysql:latest
    container_name: quote-api-db
    restart: unless-stopped
    networks:
      - quote-api-net
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-proot" ]
      interval: 5s
      retries: 10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    networks:
      - quote-api-net
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  # Open Telemetry UI
  jaeger:
    image: jaegertracing/all-in-one:1.47
    networks:
      - quote-api-net
    ports:
      - "16686:16686"

  quote-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quotedb?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - quote-api-net
    depends_on:
      db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      jaeger:
        condition: service_started

volumes:
  database:

networks:
  quote-api-net:
