########## Quote API Deployment ##########

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quote-api-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      # Wait for Redis and MySql to prevent connection issues
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 5; done;' ]

        - name: wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 5; done;' ]
      containers:
        - name: quote-api
          image: devyourid/quote-api:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.quote-api-namespace.svc.cluster.local:3306/quotedb?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SERVER_PORT
              value: "8080"
            # REDIS
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
---

########## Quote API Service ##########

apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: quote-api-namespace
spec:
  type: NodePort
  selector:
    app: quote-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080