name: Quote API CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
        # run: ./gradlew clean build -x pmdMain -x pmdTest -x checkstyleMain -x checkStyleTest -x jacocoTestReport --no-daemon

      # Run PMD
      #      - name: Run PMD
      #        run: ./gradlew pmdMain --no-daemon

      # Run Checkstyle
      #      - name: Run Checkstyle
      #        run: ./gradlew checkstyleMain --no-daemon

      # Upload test results (optional)
#      - name: Archive test results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: build/reports/tests/test

      - name: Log in to Docker Hub
        if: env.IS_MAIN_BRANCH == 'true'
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        if: env.IS_MAIN_BRANCH == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/quote-api:latest .

      - name: Push Docker image
        if: env.IS_MAIN_BRANCH == 'true'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quote-api:latest