name: Quote API CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # ----- APPLICATION STEPS ----- #

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
        # run: ./gradlew clean build -x pmdMain -x pmdTest -x checkstyleMain -x checkStyleTest -x jacocoTestReport --no-daemon

      # Run PMD
      #      - name: Run PMD
      #        run: ./gradlew pmdMain --no-daemon

      # Run Checkstyle
      #      - name: Run Checkstyle
      #        run: ./gradlew checkstyleMain --no-daemon

      # Upload test results (optional)
#      - name: Archive test results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: build/reports/tests/test

      # ----- DOCKER STEPS ----- #

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/quote-api:latest .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quote-api:latest

      # ----- KUBERNETES STEPS ----- #

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: my-cluster-name
          location: us-central1
          project_id: my-gcp-project-id

      - name: Deploy to Google Cloud Kubernetes Cluster
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl apply -f k8s/jaeger.yaml
          kubectl apply -f k8s/mysql.yaml
          kubectl apply -f k8s/otel.yaml
          kubectl apply -f k8s/quote-api.yaml
          kubectl apply -f k8s/redis.yaml

      - name: Wait for Application rollout
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl rollout status deployment/quote-api -n quote-api-namespace
